-- AlterTable
ALTER TABLE "Character" ADD COLUMN "starred" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Character" ADD COLUMN "lastBookId" TEXT REFERENCES "Book"("id") ON DELETE SET NULL ON UPDATE CASCADE;
